# Problem Set 1

##### Set up environment

In [40]:
# Set working directory
dir = "/Users/JoshuaHigbee/Box/2. Second Year/2. Winter Quarter - 2021/" *
      "Industrial Organization II - Hortacsu/Problem Sets/Problem Set 1/";
cd(dir);

# Load packages
using CSV, DataFrames, Random, Distributions, LinearAlgebra,
      LatexPrint, StatsBase, Plots, SpecialFunctions
using Optim, ForwardDiff, PyCall

# Set seed
Random.seed!(12345);

# Read in data
data = CSV.read("psetOne.csv", DataFrame);
println(names(data))

["Market", "Constant", "Price", "EngineSize", "SportsBike", "Brand2", "Brand3", "z1", "z2", "z3", "z4", "shares"]


## Question 8

##### Load data for market $t=17$, and set up parameter values (coefficient order is Price, Constant, Engine CC, BikeType, Brand2, Brand3) and $\xi$ values.

In [41]:
# Data 
d17 = data[data.Market .== 17, :];

# Parameters
θ_given =  [-3.0 1.0 1.0 2.0 -1.0 1.0]'
α = θ_given[1]

# Ownership matrix
d17.Brand1 = Ref(1.0) .- max.(d17.Brand2, d17.Brand3);
Δ = (d17.Brand1 .* d17.Brand1') .+ (d17.Brand2 .* d17.Brand2') .+ (d17.Brand3 .* d17.Brand3')

# ξ values
ξ_rand = rand(Normal(0,1),7);
ξ_newton = ξ_rand; # ξ_simple
ξ_newton = zeros(7);

##### Define useful functions for solving fixed point pricing equation.

In [42]:
# Shares function
function s_newton(price)
    X = hcat(price, d17.Constant, d17.EngineSize, d17.SportsBike, d17.Brand2, d17.Brand3)
    exp_term = X * θ_given .+ ξ_newton
    max_exp = maximum(exp_term)
    num = exp.(exp_term .- max_exp)
    return num / (exp(-max_exp) + sum(num))
end


# Jacobian of shares function
function s_Jac_newton(price)
    s = s_newton(price)
    return - α * ((s * s') .- diagm(vec(s))) # α is negative in this setting
end


# Hessian of shares function
function s_Hess_newton(price)
    s = s_newton(price)
    Hess = Array{Float64}(undef, 7, 7, 7)
    for j in 1:7
        for k in 1:7
            for l in 1:7
                Hess[j,k,l] = α^2 *
                      ((2*s[j]*s[k]*s[l] - 3*s[j]*s[k] + s[j])*(j==k && j==l) +
                      (2*s[j]*s[k]*s[l] - s[j]*s[l])*(j==k && j!=l) +
                      (2*s[j]*s[k]*s[l] - s[k]*s[l])*(j!=k && j==l) +
                      (2*s[j]*s[k]*s[l] - s[j]*s[k])*(j!=k && k==l) +
                      (2*s[j]*s[k]*s[l])*(l!=k && k!=j && j!=l))
            end
        end
    end
    return Hess
end


# Function for Newton's method (using p + Ω^{-1} * s = 0)
function f_newton(price)
    s = s_newton(price)
    s_J = s_Jac_newton(price)
    Ω = Δ .* s_J
    f = price + inv(Ω) * s
    return f
end


# Jacobian of Ω^{-1} (for use in computing Jacobian of function for fxp est)
function Ω_inv_Jac_newton(price)
    s = s_newton(price)
    s_J = s_Jac_newton(price)
    s_H = s_Hess_newton(price)
    Ω = Δ .* s_J
    Ω_J = Δ .* s_H

    Ω_J_inv = Array{Float64}(undef, length(s), length(s), length(s))
    for j in 1:length(s)
        Ω_J_inv[:,:,j] = - inv(Ω) * Ω_J[:,:,j] * inv(Ω)
    end
    return Ω_J_inv
end


# Jacobian of function for Newton's method
function f_newton_J(price)
    s = s_newton(price)
    s_J = s_Jac_newton(price)
    Ω = Δ .* s_J
    Ω_inv_J = Ω_inv_Jac_newton(price)
    Ω_inv_J_times_s = Matrix(0.0 * I, length(s), length(s))
    for j in 1:length(s)
        Ω_inv_J_times_s[:,j] = Ω_inv_J[:,:,j] * s
    end
    ∇f_newton = I + Ω_inv_J_times_s + inv(Ω) * s_J
    return ∇f_newton
end


# Actually estimate the fixed point
function newton_fxp(price, ϵ)
    diff = 1
    p_0 = price
    iter=1
    while diff > ϵ
        # Solve equation
        fxp = f_newton(p_0)
        ∇fxp = f_newton_J(p_0)
        # ∇fxp = ForwardDiff.jacobian(f_newton, p_0)
        p_1 = p_0 - inv(∇fxp) * fxp

        # Update values and loop
        diff = maximum(abs.(p_1 .- p_0))
        println("Iteration " * string(iter) * "     Difference " * string(diff))
        p_0 = p_1
        iter = iter + 1
    end
    return p_0
end

newton_fxp (generic function with 1 method)

##### Solve fixed point equation.

In [43]:
p_init = ones(7);
p_init = d17.Price;
p_optimal = newton_fxp(p_init, 1.0e-10)

println(" ")
p_optimal

Iteration 1     Difference 2.484826536163365
Iteration 2     Difference 0.2893243176990721
Iteration 3     Difference 0.0726965625358531
Iteration 4     Difference 0.006524393561025077
Iteration 5     Difference 4.2079754713597595e-5
Iteration 6     Difference 1.679278494037817e-9
Iteration 7     Difference 6.661338147750939e-16
 


7×1 Array{Float64,2}:
 0.38447413297903904
 0.3844741329790391
 0.3523194580438232
 0.3523194580438232
 1.7822602606218438
 1.782260260621844
 1.782260260621844

##### Check to ensure it is a fixed point

In [44]:
f_newton(p_optimal)
show(stdout, "text/plain", f_newton(p_optimal))

7×1 Array{Float64,2}:
 -1.1102230246251565e-16
  0.0
  0.0
 -5.551115123125783e-17
  3.9968028886505635e-15
  3.9968028886505635e-15
  3.3306690738754696e-15

## Question 9

##### Write share prediction functions.

In [717]:
# # Individual share predictor function (given mean utilities)
# function sHat_ind(;δ, X=0.0, σ, ζ=0.0, I_n=1)
    
#     # Fill values if unspecified (default)
#     if X == 0.0
#         X = repeat(fill(0.0,length(σ))', length(δ))
#     end
#     if ζ == 0.0
#         ζ = reshape(fill(0.0,length(σ)*I_n), I_n, length(σ))
#     end

#     # Construct numerators
#     const_term = repeat(δ', outer=I_n)
#     rc_term = ζ * (X .* repeat(σ, outer=length(δ)))'
#     exp_term = const_term .+ rc_term
#     max_exp = maximum(exp_term, dims=2)
#     num = exp.(exp_term - repeat(max_exp, inner=(1,length(δ))))

#     # Construct denominators and shares
#     denom = repeat(exp.(-max_exp) .+ sum(num, dims=2), inner=(1,length(δ)))
#     ŝ_i = num ./ denom
#     return ŝ_i
# end

# Individual share predictor function (given mean utilities)
function sHat_ind(;δ, X=0.0, σ, ζ=0.0, I_n=1)
    
    # Fill values if unspecified (default)
    if X == 0.0
        X = repeat(fill(0.0,length(σ))', length(δ))
    end
    if ζ == 0.0
        ζ = reshape(fill(0.0,length(σ)*I_n), I_n, length(σ))
    end

    # Construct numerators
    const_term = repeat(δ', outer=I_n)
    rc_term = ζ * (X .* repeat(σ, outer=length(δ)))'
    exp_term = const_term .+ rc_term
    num = exp.(exp_term)

    # Construct denominators and shares
    denom = repeat(Ref(1.0) .+ sum(num, dims=2), inner=(1,length(δ)))
    ŝ_i = num ./ denom
    return ŝ_i
end

# Share predictor function (for heterogeneity)
function sHat(;δ, X=0.0, σ, ζ=0.0, I_n=1)
    ŝ_i = sHat_ind(δ=δ, X=X, σ=σ, ζ=ζ, I_n=I_n)
    ŝ = 1/(I_n) * sum(ŝ_i, dims=1)
    return vec(ŝ)
end

# Share predictor function for taking ŝ after it's already computed
function sHat_from_ŝ(; ŝ_i, I_n=1)
    ŝ = 1/(I_n) * sum(ŝ_i, dims=1)
    return vec(ŝ)
end

sHat_from_ŝ (generic function with 1 method)

##### Set up parameters and data for test cases.

In [718]:
J_q9 = [3, 3, 3];
δ_q9 = [zeros(J_q9[1]), [40, 20, 20], zeros(J_q9[3])];
σ_q9 = [[0.0], [0.0], [0.1]];
X_q9 = [[], [], [repeat([1.0], 3), [1.0; 3.0; -1.0], [10.0; 10.0; -3.0]]];
I_q9 = [[], [], 50];
ζ_q9 = [[], [], reshape(rand(Normal(0,1),length(σ_q9[3])*I_q9[3]), I_q9[3], length(σ_q9[3]))];
shares_q9 = [];

##### Test all cases

In [719]:
# First case
s_test = sHat(δ=δ_q9[1], σ=σ_q9[1]);
println(s_test);
sum(s_test, dims=2)[1]
push!(shares_q9, s_test);

[0.25, 0.25, 0.25]


In [720]:
# Second case
s_test = sHat(δ=δ_q9[2], σ=σ_q9[2]);
println(s_test);
sum(s_test, dims=2)[1]
push!(shares_q9, s_test);

[0.9999999958776928, 2.0611536139418496e-9, 2.0611536139418496e-9]


In [721]:
# Third case
s_test = sHat(δ=δ_q9[3], X=X_q9[3][1], σ=σ_q9[3], ζ=ζ_q9[3], I_n=I_q9[3])
println(convert.(Float64,round.(s_test, digits=7)))
push!(shares_q9, s_test);

s_test = sHat(δ=δ_q9[3], X=X_q9[3][2], σ=σ_q9[3], ζ=ζ_q9[3], I_n=I_q9[3])
println(convert.(Float64,round.(s_test, digits=7)))
push!(shares_q9, s_test);

s_test = sHat(δ=δ_q9[3], X=X_q9[3][3], σ=σ_q9[3], ζ=ζ_q9[3], I_n=I_q9[3])
println(convert.(Float64,round.(s_test, digits=7)))
push!(shares_q9, s_test);

[0.2493036, 0.2493036, 0.2493036]
[0.2473595, 0.2477251, 0.2548299]
[0.2385902, 0.2385902, 0.2792201]


## Question 10 - - - - - - - - - CURRENTLY HAS TWO CONTRACTION MAPPING FUNCTIONS

##### Create functions for share inversion.

In [702]:
# # Contraction mapping function
# function s_contraction_map(;s, X, I_n, σ, ζ, J, L̄=1.0-1.0e-7, output=false)
#       δ_0 = convert.(Real, zeros(length(s)))
#       L = 0.5 # Initialize contraction mapping ratio
#       iter = 0 # Initialize iteration count
#       δ_diff = 0.5 # Initialize difference in δ (in case L misbehaves)
#       δ_diff_h = Array{Real}(undef, 1, 3)
#       while (δ_diff > 1.0e-7) && (L < L̄)
#             # Numerical inversion
#             δ_1 = δ_0 .+ log.(s) .- log.(sHat(δ=δ_0, X=X, σ=σ, ζ=ζ, I_n=I_n))

#             # Max distance in δ
#             δ_diff = maximum(abs.(δ_1 - δ_0))

#             # Track iterations and update Lipschitz constant every 50 iters
#             iter = iter + 1
#             if ((iter + 2) % 50) == 0
#                   δ_diff_h[1] = Real(δ_diff)
#             end
#             if ((iter + 1) % 50) == 0
#                   δ_diff_h[2] = Real(δ_diff)
#             end
#             if (iter % 50) == 0
#                   δ_diff_h[3] = Real(δ_diff)
#                   L = (δ_diff_h[2]^2) / (δ_diff_h[3] * δ_diff_h[1])
#                   if output==true
#                         println("Iteration  " * string(iter) *
#                               "    Contraction term L is " * string(L))
#                   end
#             end
#             δ_0 = δ_1
#       end

#       return δ_0
# end


# Contraction mapping function
function s_contraction_map(;s, X, I_n, σ, ζ, J, ϵ_contract = 1.0e-5, output=false)
      δ_0 = convert.(Real, zeros(length(s)))
      iter = 0 # Initialize iteration count
      δ_diff = 0.5 # Initialize difference in δ (in case L misbehaves)
      δ_diff_h = Array{Real}(undef, 1, 3)
      while (δ_diff > ϵ_contract) 
            # Numerical inversion
            δ_1 = δ_0 .+ log.(s) .- log.(sHat(δ=δ_0, X=X, σ=σ, ζ=ζ, I_n=I_n))

            # Max distance in δ
            δ_diff = maximum(abs.(δ_1 - δ_0))

            if (iter % 50) == 0 && output==true
                println("Iteration  " * string(iter) * "    Difference is " * string(δ_diff))
            end
            δ_0 = δ_1
      end

      return δ_0
end


# Log shares Jacobian function - vectorized
function log_s_Jac(; ŝ_i, I_n=1, J)
      ∫ŝ_j_mat = repeat(1/(I_n) .* sum(ŝ_i, dims=1), outer=J)'
      own_term = 1.0/(I_n) * ŝ_i' * (Ref(1.0) .- ŝ_i) .* Matrix(I, J, J)
      cross_term = -1.0/(I_n) * (ŝ_i' * ŝ_i) .* (Ref(1.0) .- Matrix(I, J, J))
      return (own_term .+ cross_term) ./ ∫ŝ_j_mat
end


# Newton's method function
function s_newton_fxp(; s, δ_0, X, I_n, σ, ζ, J, ϵ_conv=1.0e-14, output=false, maxiter = 1e5)
    diff = 0.5
    iter = 0 # Initialize iteration count
    while diff > ϵ_conv && iter < maxiter
        # Compute
        ŝ_i = sHat_ind(δ=δ_0, X=X, σ=σ, ζ=ζ, I_n=I_n)
        ŝ = sHat_from_ŝ(ŝ_i=ŝ_i, I_n=I_n)
        log_sJ = log_s_Jac(ŝ_i=ŝ_i, I_n=I_n, J=J)
        log_s = log.(ŝ)
        δ_1 = δ_0 .- inv(log_sJ) * (log_s - log.(s))

        # Check difference and iterate
        diff = maximum(abs.(δ_1 .- δ_0))
        iter = iter + 1
        if output==true
              println("Iteration  " * string(iter) *
                    "    Difference is " * string(diff))
        end
        δ_0 = δ_1
    end

    return δ_0
end


# Combine two methods function
function invert_s(; s, X, I_n, σ, ζ, J, ϵ_contract=1.0e-5, ϵ_conv=1.0e-14, output=false, maxiter_newton = 1e5)
    δ_contraction = s_contraction_map(s=s, X=X, I_n=I_n, σ=σ, ζ=ζ, J=J, ϵ_contract=ϵ_contract, output=output)
    δ = s_newton_fxp(s=s, δ_0=δ_contraction, X=X, I_n=I_n, σ=σ, ζ=ζ, J=J, ϵ_conv=ϵ_conv, output=output, 
            maxiter = maxiter_newton)
    return δ
end

invert_s (generic function with 1 method)

##### Test functions with data from market 17.

In [741]:
I_17 = 25;
X_17 = convert(Matrix, hcat(d17[:, [:Price, :Constant, :EngineSize, :SportsBike, :Brand2, :Brand3]]));
Z_17 = convert(Matrix, hcat(d17[:, [:z1, :z2, :z3, :z4]]));
σ_17 = zeros(size(X_17)[2])';
ζ_17 = reshape(rand(Normal(0,1),length(σ_17)*I_17), I_17, length(σ_17));

In [723]:
# Test contraction
δ_contract = s_contraction_map(s=d17.shares, X=X_17, I_n=I_17, σ=σ_17, ζ=ζ_17, J=size(X_17)[1])

7-element Array{Float64,1}:
  2.0697845385676574
 -0.3439439517828262
 -2.9273567831528453
  0.6068451864947533
  3.141160653013621
  1.3883038447921399
  2.3472954727255972

In [724]:
# Test Newton's method
s_newton_fxp(s=d17.shares, δ_0 = δ_contract, X=X_17, I_n=I_17, σ=σ_17, ζ=ζ_17, J=size(X_17)[1], ϵ_conv=1.0e-14)

7-element Array{Float64,1}:
  2.070264979033944
 -0.34346351131653924
 -2.9268763426865583
  0.6073256269610395
  3.1416410934799073
  1.3887842852584265
  2.3477759131918825

# CONTRACTION EPSILON IS LARGE HERE

In [725]:
# Test both
invert_s(s=d17.shares, X=X_17, I_n=I_17, σ=σ_17, ζ=ζ_17, J=size(X_17)[1], ϵ_contract=1.0e-4, ϵ_conv=1.0e-14)

7-element Array{Float64,1}:
  2.070264979033939
 -0.34346351131654446
 -2.926876342686563
  0.6073256269610349
  3.1416410934799024
  1.3887842852584218
  2.347775913191879

##### Test with data from the previous question.

In [726]:
println(invert_s(s=shares_q9[1], σ=σ_q9[2], X=0.0, I_n=1, ζ=0.0, J=J_q9[1]))
println(invert_s(s=shares_q9[2], σ=σ_q9[2], X=0.0, I_n=1, ζ=0.0, J=J_q9[2], ϵ_contract=1.0e-4))
println(invert_s(s=shares_q9[3], σ=σ_q9[3], X=X_q9[3][1], I_n=I_q9[3], ζ=ζ_q9[3], J=J_q9[3]))
println(invert_s(s=shares_q9[3], σ=σ_q9[3], X=X_q9[3][2], I_n=I_q9[3], ζ=ζ_q9[3], J=J_q9[3]))
println(invert_s(s=shares_q9[3], σ=σ_q9[3], X=X_q9[3][3], I_n=I_q9[3], ζ=ζ_q9[3], J=J_q9[3]))

[0.0, 0.0, 0.0]
[38.46485052094403, 18.464850520944033, 18.464850520944033]
[0.0, 0.0, 0.0]
[-5.6237498747096835e-5, -0.0013437516242858919, -0.030001976338485375]
[0.030934542812276183, 0.030934542812276183, -0.15380302015376077]


## Question 11

##### Write function for computing $\xi$

In [727]:
# Implicit function for ξ - all markets (X_all is vector of matrices)
function ξ_rclogit(; X_all, θ, s_all, ζ=0.0, I_num=1, maxiter_newton=1e5, rclogit_output=false)
    # θ split between linear terms (1) and nonlinear terms (2)
    αβ = θ[1] # Put price first for consistency
    σ = θ[2]
    
    # Loop through markets and invert shares
    δhat_all = []
    for mkt in 1:length(X_all)
        if rclogit_output==true
            println("Market number is " * string(mkt) * " of " * string(length(X_all)))
        end
        δhat = invert_s(s=s_all[mkt], X=X_all[mkt], I_n=I_num, σ=σ, ζ=ζ, J=length(s_all[mkt]), 
                    ϵ_contract=1.0e-3, ϵ_conv=1.0e-14, maxiter_newton = maxiter_newton)
        push!(δhat_all, δhat)
    end
    
    # Stack data and compute δ_mean
    δhat = reduce(vcat, δhat_all)
    X_stack = reduce(vcat, X_all)
    δ_mean = X_stack * αβ

    # Subtract off mean utility to get ξ̂
    return δhat .- δ_mean
end

ξ_rclogit (generic function with 1 method)

##### Write function for splicing data into markets (array of matrices and vectors, for shares and variables).

In [728]:
function mkt_X_s_break(; exclude_vec)
    X_full_mkt = []
    s_full_mkt = []
    for mkt in unique(data[[x ∉ exclude_vec for x in data.Market], :Market])
        X_mkt = convert(Matrix, data[data.Market .== mkt,
                    [:Price, :Constant, :EngineSize, :SportsBike, :Brand2, :Brand3]])
        push!(X_full_mkt, X_mkt)
        
        s_mkt = data[data.Market .== mkt, :shares]
        push!(s_full_mkt, s_mkt)
    end
    return [X_full_mkt, s_full_mkt]
end

mkt_X_s_break (generic function with 1 method)

##### Test functions with data from market.

In [729]:
# Create test parameters
I_test = 25
σ_test = zeros(6)
ζ_test = reshape(rand(Normal(0,1),length(σ_test)*I_test), I_test, length(σ_test))
Z_test = convert(Matrix, data[:, [:z1, :z2, :z3, :z4]])
W_test = inv(Z_test' * Z_test);

# Choose data
test_data = mkt_X_s_break(exclude_vec = []);

In [732]:
# Test functions at θ = 0
θ_zeros = [zeros(6), zeros(6)']
@time ξ_zeros = ξ_rclogit(X_all=test_data[1], θ=θ_test, s_all=test_data[2], ζ=ζ_test, I_num=I_test);

 23.215982 seconds (137.72 M allocations: 20.945 GiB, 21.66% gc time)


In [733]:
ξ_zeros[1:8]

8-element Array{Float64,1}:
  3.4175577069186134
  2.219989832335631
 -2.834820623687745
  4.317272874619497
  1.4596209841341568
  1.0254328494996454
  1.5368650848736907
 -2.7318744786927485

##### Write GMM objective function using implicit function $\xi$.

In [734]:
function f_gmm_rclogit_implθ(; W=I, Z, X_all, θ, s_all, ζ, I_num)
    ξ = ξ_rclogit(X_all=X_all, θ=θ, s_all=s_all, ζ=ζ, I_num=I_num)
    return (Z' * ξ)' * W * (Z' * ξ)
end

# Test objective function - computing ξ within
f_gmm_rclogit_implθ(W=W_test, Z=Z_test, X_all=test_data[1], θ=[zeros(6), zeros(6)'], s_all=test_data[2], 
    ζ=ζ_test, I_num=I_test)

252.5932803130469

##### Rewrite objective function as a function of only $\sigma$ (no linear terms)

In [735]:
# Function for computing linear parameters
function θ_tsls(; X, Z, W, δ)
    B = X' * Z * W * Z'
    return inv(B * X) * (B * δ)
end


# Function returning ξ(σ), δ(σ), and θ̄(σ)
function ξδθ_σ_rclogit(; X_all, σ, s_all, ζ=0.0, I_num=1, Z, W)
    δ = []
    for mkt in 1:length(X_all)
        δ_mkt = invert_s(s=s_all[mkt], X=X_all[mkt], I_n=I_num, σ=σ, ζ=ζ, J=length(s_all[mkt]))
        push!(δ, δ_mkt)
    end
    δ_σ_stack = reduce(vcat, δ)
    X_stack = reduce(vcat, X_all)

    αβ = θ_tsls(X=X_stack, Z=Z, W=W, δ=δ_σ_stack)

    ξ = δ_σ_stack .- (X_stack * αβ)
    return (ξ = ξ, δ_all = δ, αβ = αβ)
end


# Rewrite objective function as only a function of σ
function f_gmm_rclogit_σ(;W, Z, X_all, σ, s_all, ζ, I_num)
    output = ξδθ_σ_rclogit(X_all=X_all, σ=σ, s_all=s_all, ζ=ζ, I_num=I_num, Z=Z, W=W)
    ξ = output.ξ
    return (Z' * ξ)' * W * (Z' * ξ)
end

f_gmm_rclogit_σ (generic function with 1 method)

In [736]:
# Test objective function at σ=0
f_gmm_rclogit_σ(W=W_test, Z=Z_test, X_all=test_data[1], σ=zeros(6)', s_all=test_data[2], ζ=ζ_test, 
    I_num=I_test)

7.074969033894894

In [783]:
# Test objective function at σ=0 (only market 17)
f_gmm_rclogit_σ(W=inv(Z_17' * Z_17), Z=Z_17, X_all=[test_data[1][17]], σ=zeros(6)', s_all=[test_data[2][17]], 
    ζ=ζ_test, I_num=I_test)

2.134218946935181

In [744]:
# Test with expanded instrument set
X_no_inst = reduce(vcat, test_data[1])[:,2:6]
Z_full = hcat(X_no_inst, Z_test)
W_full = inv(Z_full' * Z_full)

9×9 Array{Float64,2}:
  0.0284132    -0.00237115   -0.0126792    …   0.00152733   -0.000417313
 -0.00237115    0.000479658   0.00100226      -0.00109375   -0.00100517
 -0.0126792     0.00100226    0.00809334      -0.000931723   0.000182673
 -0.00771592    0.00014338    0.00276867      -0.000362551   0.000154876
 -0.00332249   -0.000369468   0.000845524     -0.000244754   0.00055841
  0.00149303   -0.0011736    -0.000803375  …   0.000968919   0.000398021
  0.000499247  -0.000975531  -0.000572778     -0.00025748   -0.00036107
  0.00152733   -0.00109375   -0.000931723      0.0203565    -0.000652484
 -0.000417313  -0.00100517    0.000182673     -0.000652484   0.0203369

In [745]:
f_gmm_rclogit_σ(W=W_full, Z=Z_full, X_all=test_data[1], σ=zeros(6)', s_all=test_data[2], ζ=ζ_test, I_num=I_test)

0.7241370155056186

## Question 12

##### Write gradient function (as a function of $\sigma$ only).

In [746]:
# Individual share predictor function (given X and αβ)
function sHat_ind_αβ(; αβ, X, σ, ζ=0.0, I_n=1)
    # Construct numerators
    δ = X * αβ
    const_term = repeat(δ', outer=I_n)
    rc_term = ζ * (X .* repeat(σ, outer=length(δ)))'
    exp_term = const_term .+ rc_term
    max_exp = maximum(exp_term, dims=2)
    num = exp.(exp_term - repeat(max_exp, inner=(1,length(δ))))

    # Construct denominators and shares
    denom = repeat(exp.(-max_exp) .+ sum(num, dims=2), inner=(1,length(δ)))
    ŝ_i = num ./ denom
    return ŝ_i
end


# Function to compute Jacobian of ξ(θ) for each market
function ξ_Jac_θ_mkt(; X, I_n, ζ, ŝ_i)
    ξ_J = zeros(size(X)[1], size(X)[1])
    J_σ = zeros(size(X)[1], size(X)[2])
    for i in 1:I_n
        s = ŝ_i[i,:]
        ξ_Ji = -1.0 * ((s * s') .- diagm(vec(s)))
        ξ_J = ξ_J .+ (1/I_n) .* ξ_Ji
        J_σ = J_σ .+ (ξ_Ji * X) * diagm(ζ[i,:])
    end
    return -1.0 * inv(ξ_J) * J_σ./I_n
end


# Function for computing Jacobian of ξ(θ) for all markets
function ξ_Jac(; X_all, αβ, I_n, ζ, σ)
      ξ_J_θ = []
      for mkt in 1:length(X_all)
            X_mkt = X_all[mkt];
            ŝ_i = sHat_ind_αβ(αβ=αβ, X=X_mkt, σ=σ, ζ=ζ, I_n=I_n)
            ξ_J_θ_mkt = ξ_Jac_θ_mkt(X=X_mkt, I_n=I_n, ζ=ζ, ŝ_i=ŝ_i)
            push!(ξ_J_θ, ξ_J_θ_mkt)
      end
      ξ_J = reduce(vcat, ξ_J_θ)
      return ξ_J
end

ξ_Jac (generic function with 1 method)

##### Test function for Jacobian (first compute $\delta$ values)

In [747]:
ξδθ_output =  ξδθ_σ_rclogit(X_all=test_data[1], σ=zeros(6)', s_all=test_data[2], ζ=ζ_test, I_num=25, 
        Z=Z_test, W=W_test);

In [748]:
ξ_Jac_test = ξ_Jac(X_all=test_data[1], αβ=ξδθ_output.αβ, I_n=I_test, ζ=ζ_test, σ=zeros(6)');

In [770]:
function f_gmm_rclogit_σ_g(; X_all, αβ, Z, W, σ, I_n, ζ, ξ)
      ξ_J = ξ_Jac(X_all=X_all, αβ=αβ, I_n=I_n, ζ=ζ, σ=σ)
      df_θ = 2 * (Z' * ξ_J)' * W * (Z' * ξ)
      return df_θ
end

f_gmm_rclogit_σ_g (generic function with 1 method)

In [772]:
my_test_gmm_g = f_gmm_rclogit_σ_g(X_all=test_data[1], αβ=ξδθ_output.αβ, Z=Z_test, W=W_test, 
    σ=zeros(6)', I_n=I_test, ζ=ζ_test, ξ=ξδθ_output.ξ)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 167.999  -3.9062  -361.426  -17.5974  -1.74867  -4.98657

In [773]:
my_test_gmm_g = f_gmm_rclogit_σ_g(X_all=test_data[1], αβ=ξδθ_output.αβ, Z=Z_test, W=W_test, 
    σ=0.1*ones(6)', I_n=I_test, ζ=ζ_test, ξ=ξδθ_output.ξ)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 108.898  6.98789  -855.482  -10.4397  -3.75373  -3.2973

In [752]:
ξδθ_output_full =  ξδθ_σ_rclogit(X_all=test_data[1], σ=zeros(6)', s_all=test_data[2], ζ=ζ_test, I_num=25, 
        Z=Z_full, W=W_full);

In [753]:
my_test_gmm_g_full = f_gmm_rclogit_σ_g(X_all=test_data[1], αβ=ξδθ_output_full.αβ, Z=Z_full, W=W_full, 
    σ=zeros(6)', I_n=I_test, ζ=ζ_test, ξ=ξδθ_output_full.ξ)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 -3.39817e-12  -6.63114e-13  -1.36525e-11  …  -8.40764e-14  -5.29683e-13

In [754]:
my_test_gmm_g_full = f_gmm_rclogit_σ_g(X_all=test_data[1], αβ=ξδθ_output_full.αβ, Z=Z_full, W=W_full, 
    σ=0.1*ones(6)', I_n=I_test, ζ=ζ_test, ξ=ξδθ_output_full.ξ)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 0.176603  0.0154844  -0.517688  0.0372508  0.014842  -0.0960557

##### Test Jacobian of market shares using ForwardDiff

In [788]:
function gmm_σ_test(σ_init) 
    func = f_gmm_rclogit_σ(W=W_test, Z=Z_test, X_all=test_data[1], σ=σ_init,
                        s_all=test_data[2], ζ=ζ_test, I_num=I_test)
    return func
end
function gmm_σ_test_full(σ_init) 
    func = f_gmm_rclogit_σ(W=W_full, Z=Z_full, X_all=test_data[1], σ=σ_init,
                        s_all=test_data[2], ζ=ζ_test, I_num=I_test)
    return func
end
function gmm_σ_test_17(σ_init) 
    func = f_gmm_rclogit_σ(W=inv(Z_17' * Z_17), Z=Z_17, X_all=[test_data[1][17]], σ=σ_init,
                        s_all=[test_data[2][17]], ζ=ζ_test, I_num=I_test)
    return func
end
function gmm_σ_test_17_hybrid(σ_init) 
    func = f_gmm_rclogit_σ(W=W_test, Z=Z_17, X_all=[test_data[1][17]], σ=σ_init,
                        s_all=[test_data[2][17]], ζ=ζ_test, I_num=I_test)
    return func
end

gmm_σ_test_17_hybrid (generic function with 1 method)

# Testing market 17 data (Wtest is Z' Z in the full data, while Ztest is Z (that is, z1-z4) in the full datset.  The "full" function above uses the non-price components of X in addition to z1-z4, while the one without it just uses z1-z4.

In [790]:
ForwardDiff.gradient(gmm_σ_test_17, zeros(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 -0.477877  -0.0901108  19.6532  1.60996  -0.120795  -0.155871

In [789]:
ForwardDiff.gradient(gmm_σ_test_17_hybrid, zeros(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 0.775587  -0.00532314  1.05911  -0.00579238  0.000214525  0.0234819

In [756]:
fd_test_gmm_J = ForwardDiff.gradient(gmm_σ_test, zeros(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 -18.5407  0.848794  -58.1831  -3.29526  0.213449  0.727438

In [757]:
fd_test_gmm_J = ForwardDiff.gradient(gmm_σ_test, 0.1*ones(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 -0.600852  0.11516  17.4269  -0.600072  0.0257749  0.00282269

In [759]:
fd_test_gmm_J_full = ForwardDiff.gradient(gmm_σ_test_full, zeros(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 9.80254e-15  1.80136e-15  -3.98197e-14  …  4.40205e-16  7.56832e-15

In [760]:
fd_test_gmm_J_full = ForwardDiff.gradient(gmm_σ_test_full, 0.1*ones(6)')

1×6 Adjoint{Float64,Array{Float64,1}}:
 0.159545  0.0124774  0.9445  0.0402245  0.0411288  -0.110281

# This part below is what appears to be working ok (I think the negativity components shouldn't matter)

In [778]:
function f_gmm_rclogit_σ_g(; X_all, s_all, Z, W, σ, I_n, ζ)
    ξδθ_output =  ξδθ_σ_rclogit(X_all=X_all, σ=σ, s_all=s_all, ζ=ζ, I_num=I_n, Z=Z, W=W);
    ξ_J = ξ_Jac(X_all=X_all, αβ=ξδθ_output.αβ, I_n=I_n, ζ=ζ, σ=σ)
    df_θ = 2 * (Z' * ξ_J)' * W * (Z' * ξδθ_output.ξ)
    return df_θ
end

f_gmm_rclogit_σ_g (generic function with 1 method)

In [781]:
f_gmm_rclogit_σ_g(X_all=test_data[1], s_all=test_data[2], Z=Z_test, W=W_test, σ=zeros(6)', I_n=25, 
    ζ=ζ_test)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 167.999  -3.9062  -361.426  -17.5974  -1.74867  -4.98657

In [780]:
f_gmm_rclogit_σ_g(X_all=test_data[1], s_all=test_data[2], Z=Z_test, W=W_test, σ=0.1*ones(6)', I_n=25, 
    ζ=ζ_test)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 122.409  7.61255  -940.025  -11.6758  -4.52968  -3.75602

In [782]:
f_gmm_rclogit_σ_g(X_all=test_data[1], s_all=test_data[2], Z=Z_full, W=W_full, σ=0.1*ones(6)', I_n=25, 
    ζ=ζ_test)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 0.206239  0.0177008  -0.456702  0.0315402  0.017417  -0.107985

In [784]:
f_gmm_rclogit_σ_g(X_all=[test_data[1][17]], s_all=[test_data[2][17]], Z=Z_17, W=inv(Z_17' * Z_17), 
    σ=zeros(6)', I_n=25, ζ=ζ_test)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 -4.09185  0.104914  11.5972  0.31544  -0.0609314  0.239433

In [785]:
f_gmm_rclogit_σ_g(X_all=[test_data[1][17]], s_all=[test_data[2][17]], Z=Z_17, W=W_test, 
    σ=zeros(6)', I_n=25, ζ=ζ_test)'

1×6 Adjoint{Float64,Array{Float64,1}}:
 0.136764  -0.00405394  -0.369051  -0.0170434  -7.8023e-5  -0.00651925

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

## Question 13

##### Write GMM function that only takes in the desired values of $\sigma$ (for random coefficients on price and engine size)

In [761]:
function gmm_σ(σ_init) 
    σ_mod = [σ_init[1], 0, σ_init[2], 0, 0, 0]' # Only price and engine size have RCs
    func = f_gmm_rclogit_σ(W=W_test, Z=Z_test, X_all=test_data[1], σ=σ_mod,
                        s_all=test_data[2], ζ=ζ_test, I_num=I_test)
    return func
end

gmm_σ (generic function with 1 method)

In [762]:
# Test GMM function
gmm_σ(zeros(2)')

7.074969033894894

In [763]:
function gmm_σ_full(σ_init) 
    σ_mod = [σ_init[1], 0, σ_init[2], 0, 0, 0]' # Only price and engine size have RCs
    func = f_gmm_rclogit_σ(W=W_full, Z=Z_full, X_all=test_data[1], σ=σ_mod,
                        s_all=test_data[2], ζ=ζ_test, I_num=I_test)
    return func
end

gmm_σ_full (generic function with 1 method)

In [764]:
# Test GMM function
gmm_σ_full(zeros(2)')

0.7241370155056186

## TEMPORARILY - construct auto-diff function as placeholder for coded-up one

In [765]:
# Construct auto-diff function as placeholder
g_gmm_σ_auto = x -> ForwardDiff.gradient(gmm_σ, x)
g_gmm_σ_auto(ones(2)')

1×2 Adjoint{Float64,Array{Float64,1}}:
 822.838  3291.01

In [766]:
# Construct auto-diff function as placeholder
g_gmm_σ_auto_full = x -> ForwardDiff.gradient(gmm_σ_full, x)
g_gmm_σ_auto_full(ones(2)')

1×2 Adjoint{Float64,Array{Float64,1}}:
 -0.114101  51.1676

In [767]:
g_gmm_σ_auto_full(0.1 * ones(2)')

1×2 Adjoint{Float64,Array{Float64,1}}:
 0.130684  1.14489

##### Write function for calling one stage of GMM for a given weighting matrix.

In [768]:
function gmm_stage(; W, Z, X_all, s_all, ζ, I_num, σ_init)
    # Objective function
    function f_obj(σ_init) 
        σ_mod = [σ_init[1], 0, σ_init[2], 0, 0, 0]' # Only price and engine size have RCs
        func = f_gmm_rclogit_σ(W=W, Z=Z, X_all=X_all, σ=σ_mod, s_all=s_all, ζ=ζ, I_num=I_num)
        return func
    end
    
    # Gradient function
#     function g_obj(σ_init)
#         σ_mod = [σ_init[1], 0, σ_init[2], 0, 0, 0]' # Only price and engine size have RCs
#         grad = f_gmm_rclogit_σ_g(W=W, Z=Z, X_all=X_all, σ=σ_mod, s_all=s_all, ζ=ζ, I_num=I_num) 
#         G[1:2] = grad[1,3]
#     end
    
    # AD gradient function
    g_gmm_σ_auto_test = x -> ForwardDiff.gradient(f_obj, x)
    function g_obj(G, σ_init)
        grad = g_gmm_σ_auto_test(σ_init)
        G[1:2] = grad[1:2]
    end
    
    # Return result
    σ_result = Optim.minimizer(optimize(f_obj, g_obj, σ_init, BFGS(), Optim.Options(show_trace=true)))
    return σ_result
end  

gmm_stage (generic function with 1 method)

In [769]:
gmm_stage(W=W_full, Z=Z_full, X_all=test_data[1], s_all=test_data[2], ζ=ζ_test, I_num=I_test, 
    σ_init=0.1*ones(2))

Iter     Function value   Gradient norm 
     0     7.801446e-01     1.144892e+00
 * time: 0.0007359981536865234
     1     7.664995e-01     9.297282e-01
 * time: 51.830342054367065
     2     7.288072e-01     2.575596e-01
 * time: 156.80731296539307
     3     7.243450e-01     3.826922e-02
 * time: 196.7523410320282
     4     7.241371e-01     7.535814e-04
 * time: 257.3205749988556
     5     7.241370e-01     5.741963e-06
 * time: 362.20552682876587
     6     7.241370e-01     1.438635e-11
 * time: 434.5701470375061


2-element Array{Float64,1}:
  2.912537762558837e-12
 -1.7766381381950007e-12

In [ ]:
gmm_stage(W=W_full, Z=Z_full, X_all=test_data[1], s_all=test_data[2], ζ=ζ_test, I_num=I_test, 
    σ_init=0.1*ones(2)))

##### Write functions for implementing two-stage GMM.

In [ ]:
# Function for optimal weighting matrix
function gmm_opt_weight(; Z, ξ)
    n = size(Z)[1]
    Zξ = Z' * ξ
    return inv((1/n) * Zξ * Zξ')
end


# Function for gradient of ξ with respect to all parameters - STILL NEED TO FINISH THIS!!!!!!!!!!!!!!!!!!!!!!!
function ξ_θfull_J(; Z, ξ)
    n = size(Z)[1]
    Zξ = Z' * ξ
    return inv((1/n) * Zξ * Zξ')
end


# Function for two-stage GMM
function two_stage_gmm(; W_stage1, Z, X_all, s_all, ζ, I_num, σ_init)
    # First stage estimation with given starting weighting matrix
    σ_stage1 = gmm_stage(W=W_stage1, Z=Z, X_all=X_all, s_all=s_all, ζ=ζ, I_num=I_num, σ_init=σ_init)
    
    # Compute optimal weighting matrix for second stage
    ξδθ_output =  ξδθ_σ_rclogit(X_all=X_all, σ=σ_stage1, s_all=s_all, ζ=ζ, I_num=I_num, Z=Z, W=W_stage1)
    ξ_stage1 = ξδθ_output.ξ
    W_stage2 = gmm_opt_weight(Z=Z, ξ=ξ_stage1)
    
    # Second stage estimation with given starting weighting matrix
    σ_stage2 = gmm_stage(W=W_stage2, Z=Z, X_all=X_all, s_all=s_all, ζ=ζ, I_num=I_num, σ_init=σ_stage1)
    
    # Compute covariance matrix for point estimates
    G = ξ_θfull_J(Z, ξ) # STILL NEED TO FINISH THIS HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ξδθ_output =  ξδθ_σ_rclogit(X_all=X_all, σ=σ_stage1, s_all=s_all, ζ=ζ, I_num=I_num, Z=Z, W=W_stage1)
    ξ_stage1 = ξδθ_output.ξ
    W_stage2 = gmm_opt_weight(Z=Z, ξ=ξ_stage1)
    Σ = inv(G' * inv(W_stage2) * G)
    
    # Return values
    return (σ = σ_stage2, αβ = ξδθ_output.αβ, Σ = Σ)
end

## Question 14

##### Use PyBLP

In [518]:
pyblp = pyimport("pyblp")
np = pyimport("numpy")
pd = pyimport("pandas")
os = pyimport("os")

PyObject <module 'os' from '/Users/JoshuaHigbee/.julia/conda/3/lib/python3.8/os.py'>

In [520]:
os.getcwd()

"/Users/JoshuaHigbee/Box/2. Second Year/2. Winter Quarter - 2021/Industrial Organization II - Hortacsu/Problem Sets/Problem Set 1"

In [580]:
product_data = pd.read_csv("psetOne.csv")

PyObject       Market  Constant     Price  ...        z3        z4    shares
0          1         1  1.554708  ...  0.034361  0.056459  0.239077
1          1         1  1.559811  ...  0.326445  0.062091  0.072184
2          1         1  1.857186  ...  0.075316  0.278736  0.000460
3          1         1  1.995438  ...  0.345850  0.084891  0.587867
4          1         1  4.017987  ...  0.652134  0.509693  0.033746
...      ...       ...       ...  ...       ...       ...       ...
1042     150         1  2.010710  ...  0.095527  0.185333  0.000548
1043     150         1  2.001591  ...  0.285886  0.263406  0.024166
1044     150         1  1.692977  ...  0.079379  0.276368  0.355868
1045     150         1  2.337965  ...  0.695795  0.044509  0.347937
1046     150         1  4.683845  ...  0.225896  0.692309  0.008260

[1047 rows x 12 columns]

In [581]:
product_data.rename(columns=Dict("Price"=>"prices", "Market"=>"market_ids", "z1"=>"demand_instruments0",
        "z2"=>"demand_instruments1", "z3"=>"demand_instruments2", "z4"=>"demand_instruments3"), inplace="True")

In [588]:
product_formulations = (pyblp.Formulation("prices + 1 + EngineSize + SportsBike + Brand2 + Brand3"),
   pyblp.Formulation("0 + prices + EngineSize"))

(PyObject 1 + prices + EngineSize + SportsBike + Brand2 + Brand3, PyObject prices + EngineSize)

In [589]:
mc_integration = pyblp.Integration("monte_carlo", size=25, specification_options=Dict("seed"=>12345))

PyObject Configured to construct nodes and weights with Monte Carlo simulation with options {seed: 12345}.

In [590]:
problem = pyblp.Problem(product_formulations, product_data, integration=mc_integration, add_exogenous="True")

PyObject Dimensions:
 T    N     I     K1    K2    MD 
---  ----  ----  ----  ----  ----
150  1047  3750   6     2     9  

Formulations:
       Column Indices:           0         1           2           3         4       5   
-----------------------------  ------  ----------  ----------  ----------  ------  ------
 X1: Linear Characteristics      1       prices    EngineSize  SportsBike  Brand2  Brand3
X2: Nonlinear Characteristics  prices  EngineSize                                        

In [591]:
bfgs = pyblp.Optimization("bfgs", Dict("gtol"=>1e-4))

PyObject Configured to optimize using the BFGS algorithm implemented in SciPy with analytic gradients and options {gtol: +1.000000E-04}.

# INITIALIZE STARTING VALUES

In [595]:
results = problem.solve(sigma=np.identity(2), optimization=bfgs)

Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initializing the problem ...
Initialized the problem after 00:00:00.

Dimensions:
 T    N     I     K1    K2    MD 
---  ----  ----  ----  ----  ----
150  1047  3750   6     3     9  

Formulations:
       Column Indices:          0     1         2           3         4       5   
-----------------------------  ---  ------  ----------  ----------  ------  ------
 X1: Linear Characteristics     1   prices  EngineSize  SportsBike  Brand2  Brand3
X2: Nonlinear Characteristics   1   prices  EngineSize                            
Initializing the problem ...
Initialized the problem after 00:00:00.

Dimensions:
 T    N     I     K1    K2    MD 
---  ----  ----  ----  ----  ----
150  1047  3750   6     2     9  

Formulations:
       Co

PyObject Problem Results Summary:
GMM     Objective      Gradient         Hessian         Hessian     Clipped  Weighting Matrix  Covariance Matrix
Step      Value          Norm       Min Eigenvalue  Max Eigenvalue  Shares   Condition Number  Condition Number 
----  -------------  -------------  --------------  --------------  -------  ----------------  -----------------
 2    +6.512462E+01  +2.867143E+02  -2.099711E+09   +1.609858E+10      0      +1.565485E+04      +7.208606E+04  

Cumulative Statistics:
Computation  Optimizer  Optimization   Objective   Fixed Point  Contraction
   Time      Converged   Iterations   Evaluations  Iterations   Evaluations
-----------  ---------  ------------  -----------  -----------  -----------
 00:03:01       No           5            48         300660       909254   

Nonlinear Coefficient Estimates (Robust SEs in Parentheses):
  Sigma:        prices         EngineSize   
----------  ---------------  ---------------
  prices     +8.177060E-01        

## Question 15

##### Elasticity matrix for market $t=17$.